### ISSUE TITLE
Screenshots are randomly sized in the screenshots menu

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhoneCompanion#1]
- Screenshots are not of same size

- They could be sized the same to fit their window, i think the Slovenian screenshot here looks the best size (border)

![E93bqOeM2s](https://user-images.githubusercontent.com/50620416/68026233-5827f200-fcaf-11e9-83ab-5fc62acb1293.png)

**Comment by UriahShaulMandel** [comment]
Hi, the screenshots are randomly sized because they work using Markup Table, and the header of the table decides how big it's column will be.
This is not a wanted behavior, and I'm planning on converting this mechanism to html based one, which won't do such problems. doing that will fix this and #2
