### ISSUE TITLE
Add a horizontal scroll bar at the top of the screenshots

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhoneCompanion#2]
![a7Jf8hIZQd](https://user-images.githubusercontent.com/50620416/68026373-d4223a00-fcaf-11e9-918f-d71c69ae07a5.png)

**Comment by UriahShaulMandel** [comment]
Hi, the scroll bar is down because this system works using Markup Table, and it doesn't allow playing with such features.
This is not a wanted behavior, and I'm planning on converting this mechanism to html based one, which won't do such problems. doing that will fix this and #1
